name: build-windows

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
      - name: Set build version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "BUILD_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "BUILD_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi
      - name: Build
        shell: cmd
        run: gcc src\main.c src\app.c src\downloader.c src\config.c resources\app.rc -o version-download-tool.exe -mwindows -lcomctl32 -lwinhttp -D BUILD_VERSION=\"%BUILD_VERSION%\"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-download-tool
          path: version-download-tool.exe

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          files: version-download-tool.exe
